(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function profile(){const x=(()=>{try{return localStorage.getItem('itp26-program-mode')}catch(e){return null}})();return x==='yulia'?'yulia':'vlad'}
function toMin(t){const a=(t||'').split(':').map(Number);return (a[0]||0)*60+(a[1]||0)}
function planHas(e,p){const a=Array.isArray(e.plan)?e.plan:[];return a.includes('both')||a.includes(p)}
function route(p){return (window.ITP_SCHEDULE?.events||[]).filter(e=>planHas(e,p)).sort((a,b)=>toMin(a.start)-toMin(b.start))}
function currentNext(p){const es=route(p),n=new Date(),m=n.getHours()*60+n.getMinutes();if(!(n.getFullYear()===2026&&n.getMonth()===7&&n.getDate()===8))return{current:null,next:es[0]||null};return{current:es.find(e=>m>=toMin(e.start)&&m<toMin(e.end||e.start)),next:es.find(e=>toMin(e.start)>m)}}
function loc(e){return e?.locationId&&window.ITP_SCHEDULE?.locations?.[e.locationId]}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function styles(){if($('#mapUxStyles'))return;const s=document.createElement('style');s.id='mapUxStyles';s.textContent=`
body.map-screen .top{display:none}body.map-screen .app{padding-top:calc(7px + env(safe-area-inset-top));padding-left:9px;padding-right:9px}body.map-screen #map{min-height:calc(100svh - 82px)}
.map-screen-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 2px 7px}.map-screen-head h2{font-size:24px}.map-profile{display:flex;gap:4px;padding:3px;background:var(--card);border:1px solid var(--border);border-radius:12px}.map-profile button{border:0;background:transparent;color:var(--muted);border-radius:9px;padding:7px 9px;font-size:12px;font-weight:800}.map-profile button.active{background:var(--card2);color:var(--text)}
#map .geo-switch{position:sticky;top:calc(5px + env(safe-area-inset-top));z-index:46;margin:0 0 7px;background:rgba(23,23,25,.94);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);box-shadow:0 5px 18px rgba(0,0,0,.18)}
#festivalGeoPane{display:flex;flex-direction:column;gap:7px}#festivalGeoPane .map-shell{order:2;margin:0}#festivalGeoPane #mapNowCard{order:1}#festivalGeoPane .map-result{order:3;margin:0}#festivalGeoPane #gpsBox{order:4;margin:0}#festivalGeoPane #mapMore{order:5}
.map-now{padding:11px 12px;border:1px solid #315f83;background:linear-gradient(145deg,#0d2438,var(--card));border-radius:15px}.map-now-top{display:flex;justify-content:space-between;gap:8px}.map-now-label{font-size:11px;color:#8fcaef;font-weight:800}.map-now-title{font-size:15px;font-weight:850;margin-top:2px}.map-now-meta{font-size:11px;color:var(--muted);margin-top:3px}.map-now-actions{display:flex;gap:6px;margin-top:8px}.map-now-actions button{border:1px solid #315f83;background:#15344f;color:#dff2ff;border-radius:10px;padding:8px 10px;font-size:11px;font-weight:800}.map-now-actions button.primary{background:#1688ff;border-color:#1688ff;color:#fff}
#festivalGeoPane .map-viewport{height:min(55svh,520px);min-height:360px;aspect-ratio:auto}#festivalGeoPane .map-shell{border-radius:16px}.map-expand{width:37px!important}.map-shell.map-expanded{position:fixed!important;inset:calc(7px + env(safe-area-inset-top)) 7px calc(7px + env(safe-area-inset-bottom)) 7px;z-index:120;border-radius:18px!important;background:#0f0f10}.map-shell.map-expanded .map-viewport{height:100%!important;min-height:0!important}.map-shell.map-expanded .map-toolbar{z-index:130}
.map-more{border:1px solid var(--border);border-radius:14px;background:var(--card);overflow:hidden}.map-more summary{list-style:none;padding:11px 12px;color:var(--text);font-weight:800;cursor:pointer}.map-more summary::-webkit-details-marker{display:none}.map-more summary:after{content:'⌄';float:right;color:var(--muted)}.map-more[open] summary:after{content:'⌃'}.map-more-body{padding:0 9px 9px}.map-more .map-tools,.map-more .map-zones{margin-top:7px}
#yandexGeoPane{display:flex;flex-direction:column;gap:7px}#yandexGeoPane .yandex-map-wrap{order:1;margin:0;min-height:0;height:min(58svh,540px)}#yandexGeoPane #itpYandexConstructorMap,#yandexGeoPane .yandex-static-base{height:100%!important}#yandexGeoPane .yandex-actions{order:2;margin:0}#yandexGeoPane .yandex-intro{order:3;margin:0}#yandexGeoPane .entrance-title{order:4;margin:8px 2px 0}#yandexGeoPane .entrance-grid{order:5}#yandexGeoPane .ops-note{order:6;margin:0}#yandexGeoPane .yandex-help{order:7;margin:0}.yandex-expand{position:absolute;right:8px;top:8px;z-index:9;border:1px solid rgba(0,0,0,.15);background:rgba(255,255,255,.94);border-radius:10px;width:38px;height:38px;font-weight:900}.yandex-map-wrap.map-expanded{position:fixed!important;inset:calc(7px + env(safe-area-inset-top)) 7px calc(7px + env(safe-area-inset-bottom)) 7px;z-index:120;height:auto!important;border-radius:18px}
.route-svg{position:absolute;inset:0;width:100%;height:100%;z-index:15;pointer-events:none;overflow:visible}.route-path-shadow{fill:none;stroke:rgba(0,0,0,.55);stroke-width:10;stroke-linecap:round;stroke-linejoin:round}.route-path{fill:none;stroke:#1688ff;stroke-width:5;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:12 8}.route-start{fill:#1688ff;stroke:#fff;stroke-width:3}.route-end{fill:#ff7a00;stroke:#111;stroke-width:3}
@media(max-width:390px){#festivalGeoPane .map-viewport{height:min(52svh,470px);min-height:335px}.map-screen-head h2{font-size:22px}.map-now-title{font-size:14px}}
`;document.head.appendChild(s)}
function setProfile(p){const tab=$('.pv2-tab[data-pmode="'+p+'"]');if(tab){tab.click()}else{try{localStorage.setItem('itp26-program-mode',p)}catch(e){}document.dispatchEvent(new CustomEvent('itp:profile-change',{detail:{profile:p}}))}renderHead();renderNow()}
function renderHead(){const h=$('#mapScreenHead');if(!h)return;const p=profile();$$('[data-map-profile]',h).forEach(b=>b.classList.toggle('active',b.dataset.mapProfile===p))}
function renderNow(){const box=$('#mapNowCard');if(!box)return;const p=profile(),ci=currentNext(p),e=ci.current||ci.next,l=loc(e),state=ci.current?'Сейчас':'Дальше';if(!e){box.innerHTML='<div class="map-now-title">Маршрут на сегодня завершён</div>';return}box.innerHTML=`<div class="map-now-top"><div><div class="map-now-label">${p==='vlad'?'👨 Влад':'👩 Юля'} · ${state}</div><div class="map-now-title">${esc(ci.current?'':e.start+' · ')}${esc(e.title)}</div><div class="map-now-meta">${esc(l?.title||e.company||'')}</div></div></div><div class="map-now-actions">${l?`<button class="primary" id="mapRouteNow" type="button">🧭 Путь</button><button id="mapFocusNow" type="button">📍 Показать</button>`:''}${window.ITP_GEO_UI?'<button id="mapYandexNow" type="button">Яндекс</button>':''}</div>`;$('#mapRouteNow')?.addEventListener('click',()=>window.ITP_ROUTE_MAP?.routeToLocation?.(e.locationId));$('#mapFocusNow')?.addEventListener('click',()=>focusLocation(e.locationId));$('#mapYandexNow')?.addEventListener('click',()=>window.ITP_GEO_UI?.openYandex?.())}
function focusLocation(locationId){const l=window.ITP_SCHEDULE?.locations?.[locationId];if(!l)return;window.ITP_GEO_UI?.openFestival?.();const all=$('#mapFilters [data-filter="all"]');all?.click();setTimeout(()=>$('#mapPins .map-pin[data-id="'+l.mapId+'"]')?.click(),40)}
function restructure(){const map=$('#map'),sw=$('#geoSwitch'),f=$('#festivalGeoPane'),y=$('#yandexGeoPane');if(!map||!sw||!f||!y)return false;if(!$('#mapScreenHead')){const h=document.createElement('div');h.id='mapScreenHead';h.className='map-screen-head';h.innerHTML='<h2>Карта</h2><div class="map-profile"><button type="button" data-map-profile="vlad">👨 Влад</button><button type="button" data-map-profile="yulia">👩 Юля</button></div>';map.insertBefore(h,map.firstChild);$$('[data-map-profile]',h).forEach(b=>b.addEventListener('click',()=>setProfile(b.dataset.mapProfile)))}map.insertBefore(sw,$('#mapScreenHead').nextSibling);if(!$('#mapNowCard')){const n=document.createElement('div');n.id='mapNowCard';n.className='map-now';f.insertBefore(n,f.firstChild)}const shell=$('.map-shell',f);if(shell){f.insertBefore(shell,$('#mapNowCard').nextSibling);const tb=$('.map-toolbar',shell);if(tb&&!$('.map-expand',tb)){const b=document.createElement('button');b.type='button';b.className='map-expand';b.textContent='⛶';b.title='На весь экран';b.addEventListener('click',()=>{shell.classList.toggle('map-expanded');b.textContent=shell.classList.contains('map-expanded')?'✕':'⛶'});tb.appendChild(b)}}const result=$('.map-result',f);if(result&&shell)f.insertBefore(result,shell.nextSibling);let more=$('#mapMore');if(!more){more=document.createElement('details');more.id='mapMore';more.className='map-more';more.innerHTML='<summary>Поиск, фильтры и зоны</summary><div class="map-more-body"></div>';f.appendChild(more)}const body=$('.map-more-body',more);['.map-tools','.map-zones','.map-reading','.map-list','.map-hint','.map-legend-mini','.map-route-note'].forEach(sel=>{const el=$(sel,f);if(el&&!body.contains(el))body.appendChild(el)});const gps=$('#gpsBox',f);if(gps&&result)f.insertBefore(gps,result.nextSibling);const yw=$('.yandex-map-wrap',y);if(yw&&!$('.yandex-expand',yw)){const b=document.createElement('button');b.type='button';b.className='yandex-expand';b.textContent='⛶';b.addEventListener('click',()=>{yw.classList.toggle('map-expanded');b.textContent=yw.classList.contains('map-expanded')?'✕':'⛶'});yw.appendChild(b)}renderHead();renderNow();return true}
function screenState(){document.body.classList.toggle('map-screen',!!$('#tab-map')?.checked);if($('#tab-map')?.checked)setTimeout(()=>{restructure();renderNow()},20)}
function init(){styles();let tries=0;const t=setInterval(()=>{tries++;if(restructure()||tries>80)clearInterval(t)},50);$$('input[name="tab"]').forEach(x=>x.addEventListener('change',screenState));document.addEventListener('itp:profile-change',()=>{renderHead();renderNow()});setInterval(renderNow,60000);screenState();const obs=new MutationObserver(()=>restructure());const map=$('#map');if(map)obs.observe(map,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();