(function(){
'use strict';
const N={e1:[14,40],w1:[24,45],eng:[30,42],w2:[36,48],north:[48,39],upper:[51,29],gen:[54,24],n2:[68,20],e2:[81,8],center:[48,57],south:[46,69],team:[43,73],auto:[50,66],flat:[64,75],stage:[27,86],east:[68,55],prod:[86,53],e3:[94,46],science:[81,24],edu:[53,35]};
const E=[['e1','w1'],['w1','eng'],['eng','w2'],['w2','north'],['w2','center'],['north','edu'],['north','upper'],['upper','gen'],['gen','n2'],['n2','e2'],['n2','science'],['science','prod'],['center','east'],['east','prod'],['prod','e3'],['center','south'],['south','team'],['south','auto'],['south','stage'],['south','flat'],['flat','east'],['edu','upper'],['edu','center'],['auto','east'],['team','stage']];
const POI={entr1:'e1',entr4:'w1',eng3:'eng',cyber4:'w2',tproducts:'w2',education:'edu',big5:'upper',gen6:'gen',entr2:'e2',science:'science',prod1:'prod',data2:'prod',entr3:'e3',team:'team',tech:'south',auto:'auto',flat:'flat',mainstage:'stage'};
const G={};Object.keys(N).forEach(k=>G[k]=[]);function d(a,b){const A=N[a],B=N[b];return Math.hypot((A[0]-B[0])*1.05,A[1]-B[1])}E.forEach(([a,b])=>{const w=d(a,b);G[a].push([b,w]);G[b].push([a,w])});
function pin(mapId){const e=document.querySelector('#mapPins .map-pin[data-id="'+mapId+'"]');if(!e)return null;return{x:parseFloat(e.style.left),y:parseFloat(e.style.top),id:mapId}}
function gps(){const e=document.getElementById('gpsDot');if(!e||e.hidden)return null;const x=parseFloat(e.style.left),y=parseFloat(e.style.top);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}
function nearest(p){let best=null,bd=1e9;for(const [k,a] of Object.entries(N)){const z=Math.hypot((p.x-a[0])*1.05,p.y-a[1]);if(z<bd){bd=z;best=k}}return best}
function shortest(a,b){const dist={},prev={},q=new Set(Object.keys(N));Object.keys(N).forEach(k=>dist[k]=Infinity);dist[a]=0;while(q.size){let u=null,du=Infinity;q.forEach(k=>{if(dist[k]<du){du=dist[k];u=k}});if(u==null)break;q.delete(u);if(u===b)break;for(const [v,w] of G[u])if(q.has(v)&&du+w<dist[v]){dist[v]=du+w;prev[v]=u}}const path=[];let x=b;if(dist[x]===Infinity)return[];while(x){path.unshift(x);if(x===a)break;x=prev[x]}return path}
function ensure(){const stage=document.getElementById('mapStage');if(!stage)return null;let s=document.getElementById('routeSvg');if(!s){s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.id='routeSvg';s.setAttribute('class','route-svg');s.setAttribute('viewBox','0 0 1200 1136');s.setAttribute('preserveAspectRatio','none');stage.insertBefore(s,document.getElementById('mapPins'));}return s}
function clear(){const s=document.getElementById('routeSvg');if(s)s.innerHTML=''}
function point(p){return[p.x/100*1200,p.y/100*1136]}
function draw(start,end,path){const s=ensure();if(!s)return;const pts=[start,...path.map(k=>({x:N[k][0],y:N[k][1]})),end];const clean=pts.filter((p,i,a)=>i===0||Math.hypot(p.x-a[i-1].x,p.y-a[i-1].y)>.5);const xy=clean.map(point);const str=xy.map(v=>v.join(',')).join(' ');const last=xy[xy.length-1];s.innerHTML=`<polyline class="route-path-shadow" points="${str}"/><polyline class="route-path" points="${str}"/><circle class="route-start" cx="${xy[0][0]}" cy="${xy[0][1]}" r="8"/><circle class="route-end" cx="${last[0]}" cy="${last[1]}" r="10"/>`}
function currentStart(){const g=gps();if(g)return g;const p=(()=>{try{return localStorage.getItem('itp26-program-mode')==='yulia'?'yulia':'vlad'}catch(e){return'vlad'}})();const es=(window.ITP_SCHEDULE?.events||[]).filter(e=>{const a=Array.isArray(e.plan)?e.plan:[];return(a.includes('both')||a.includes(p))&&e.locationId}).sort((a,b)=>a.start.localeCompare(b.start));const n=new Date(),m=n.getHours()*60+n.getMinutes(),tm=t=>{const z=t.split(':').map(Number);return z[0]*60+z[1]};const cur=es.find(e=>m>=tm(e.start)&&m<tm(e.end||e.start));if(cur){const l=window.ITP_SCHEDULE.locations[cur.locationId];return pin(l.mapId)}return null}
function routeToLocation(locationId){window.ITP_GEO_UI?.openFestival?.();const l=window.ITP_SCHEDULE?.locations?.[locationId];if(!l)return false;const end=pin(l.mapId);if(!end)return false;let start=currentStart();if(!start){const selected=document.querySelector('#mapPins .map-pin.selected');if(selected)start={x:parseFloat(selected.style.left),y:parseFloat(selected.style.top)}}if(!start){document.querySelector('#mapPins .map-pin[data-id="'+l.mapId+'"]')?.click();return false}const a=nearest(start),b=POI[l.mapId]||nearest(end),path=shortest(a,b);draw(start,end,path);document.querySelector('#mapPins .map-pin[data-id="'+l.mapId+'"]')?.click();const cost=path.length>1?path.slice(1).reduce((sum,k,i)=>sum+d(path[i],k),0):0;const mins=Math.max(1,Math.round(cost/7.5));document.dispatchEvent(new CustomEvent('itp:route-drawn',{detail:{locationId,minutes:mins}}));return true}
function next(){const p=(()=>{try{return localStorage.getItem('itp26-program-mode')==='yulia'?'yulia':'vlad'}catch(e){return'vlad'}})(),es=(window.ITP_SCHEDULE?.events||[]).filter(e=>{const a=Array.isArray(e.plan)?e.plan:[];return(a.includes('both')||a.includes(p))&&e.locationId}).sort((a,b)=>a.start.localeCompare(b.start)),n=new Date(),m=n.getHours()*60+n.getMinutes(),tm=t=>{const z=t.split(':').map(Number);return z[0]*60+z[1]},e=es.find(x=>tm(x.start)>m)||es.find(x=>m>=tm(x.start)&&m<tm(x.end||x.start));return e?routeToLocation(e.locationId):false}
window.ITP_ROUTE_MAP={routeToLocation,routeToNext:next,clear};document.addEventListener('itp:profile-change',clear);
})();